"""The single trusted source and the single validator for stored
notification ``target_path`` values (M14).

Two rules make a notification target safe:

1. **Every target is generated by server code here.** No producer builds
   a path by string concatenation and no request value ever reaches
   ``Notification.target_path``. The builders below take only already-
   known public ids and resolve the path through the application's
   own URL map, so a route rename can never silently leave a dangling
   hand-written string.
2. **Every target is validated twice** -- once before it is stored, and
   again every time a notification is opened, because a row can outlive
   the code that wrote it (and could in principle be edited directly in
   the database). :func:`validate_notification_target` is fail-closed:
   it accepts only a single-leading-slash, same-origin relative path that
   already lives inside the recipient role's own URL namespace, and
   rejects everything else rather than trying to repair it.

This is deliberately stricter than
``app.security.redirects.get_safe_redirect_target`` (which answers "may I
redirect a *user-supplied* ``next`` value?"). A notification target must
additionally be **role-namespaced** -- a Student notification may only
ever point under ``/student/`` and a Teacher notification only under
``/teacher/`` -- and must contain no query string and no ``.``/``..``
segment a browser would normalise back out of that namespace. Passing
this validator is **not** an authorization decision: the open route still
re-authorizes the destination from scratch on every request, and an old
notification is never proof of current access.
"""

from urllib.parse import urlparse

from flask import current_app

from app.models import UserRole

_CONTROL_CHARS = frozenset(chr(c) for c in range(0x20)) | {chr(0x7F)}

#: Maximum stored length -- matches ``notifications.target_path``.
MAX_TARGET_LENGTH = 512

#: The only URL namespace each recipient role may be sent to.
ROLE_NAMESPACES = {
    UserRole.STUDENT.value: "/student/",
    UserRole.TEACHER.value: "/teacher/",
}

#: Characters allowed in an optional fragment (``#material-<public_id>``).
#: Anything else -- including ``/``, ``?``, ``%`` and ``\`` -- is rejected
#: rather than escaped.
_FRAGMENT_ALLOWED = frozenset(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_."
)


def validate_notification_target(role, candidate):
    """Return `candidate` when it is a safe stored target for a recipient
    whose role is `role`, else ``None``.

    Accepted: a non-empty string of at most :data:`MAX_TARGET_LENGTH`
    characters, beginning with the role's own namespace prefix, made only
    of ordinary path segments, optionally followed by a simple ``#``
    fragment.

    Rejected -- with no attempt to sanitise or "fix" the value:

    - a role that has no namespace at all (Administrator / Researcher /
      anything unknown), so a notification can never be opened by a role
      that is not supposed to have an inbox;
    - absolute (``https://evil.example``) and protocol-relative
      (``//evil.example/x``) URLs, and anything ``urlparse`` reads as
      carrying a scheme or a network location;
    - backslashes, which some browsers reinterpret as part of the
      authority;
    - control characters (including embedded newlines, which would also
      be a header-injection vector);
    - a query string;
    - a ``.`` or ``..`` segment, which a browser would normalise -- so
      ``/student/../teacher/dashboard`` can never leave the namespace;
    - anything outside the recipient role's namespace, including the
      namespace name used as a bare prefix (``/studentx/...``).
    """
    namespace = ROLE_NAMESPACES.get(role)
    if namespace is None:
        return None
    if not candidate or not isinstance(candidate, str):
        return None
    if len(candidate) > MAX_TARGET_LENGTH:
        return None
    if any(ch in _CONTROL_CHARS for ch in candidate):
        return None
    if "\\" in candidate:
        return None
    if not candidate.startswith("/") or candidate.startswith("//"):
        return None

    parsed = urlparse(candidate)
    if parsed.scheme or parsed.netloc or parsed.query or parsed.params:
        return None
    if parsed.fragment and not set(parsed.fragment) <= _FRAGMENT_ALLOWED:
        return None

    path = parsed.path
    if not path.startswith(namespace):
        return None
    segments = path.split("/")
    if any(segment in (".", "..") for segment in segments):
        return None
    if any(not segment for segment in segments[1:]):
        # An empty interior/trailing segment means a doubled or trailing
        # slash -- not a shape this application ever generates.
        return None
    return candidate


def _build_path(endpoint, **values):
    """Resolve one of this application's own endpoints to a relative path.

    Goes through the URL map rather than plain string formatting, so a
    renamed or removed route fails loudly here instead of quietly storing
    a dead target. Deliberately **not** Flask's request-bound URL helper:
    a producer runs after its domain commit and must not depend on an
    active request context (that helper raises outside one unless
    ``SERVER_NAME`` is configured), so a future non-request caller would
    otherwise lose every notification silently. The bound host is a
    throwaway -- ``force_external=False`` returns the path alone, and the
    result is validated before it can be stored.
    """
    return current_app.url_map.bind("localhost").build(
        endpoint, values, force_external=False
    )


def _validated(role, path):
    """Validate a freshly built target before it is ever stored.

    A failure here means the *builder* is wrong (a route was renamed, or
    a caller passed something that is not a public id), never that user
    input was rejected -- so it raises rather than silently storing an
    unusable value. Producers run inside the best-effort delivery wrapper,
    which catches this, logs it, and leaves the already-committed domain
    mutation untouched.
    """
    safe = validate_notification_target(role, path)
    if safe is None:
        raise ValueError(f"Refusing to store an unsafe notification target for role {role!r}")
    return safe


def student_dashboard_target():
    """Where an enrollment / schedule notification sends a Student."""
    return _validated(UserRole.STUDENT.value, _build_path("student.dashboard"))


def teacher_dashboard_target():
    """Where an assignment / schedule notification sends a Teacher."""
    return _validated(UserRole.TEACHER.value, _build_path("teacher.dashboard"))


def role_dashboard_target(role):
    """The dashboard target for `role`, or ``None`` for a role without an
    inbox. Used by the Schedule producer, whose recipients are a mix of
    Students and Teachers.
    """
    if role == UserRole.STUDENT.value:
        return student_dashboard_target()
    if role == UserRole.TEACHER.value:
        return teacher_dashboard_target()
    return None


def student_lesson_target(group_public_id, unit_public_id, lesson_public_id):
    """The authorized Student Lesson page for a published Lesson."""
    return _validated(
        UserRole.STUDENT.value,
        _build_path(
            "student.lesson_detail",
            group_public_id=group_public_id,
            unit_public_id=unit_public_id,
            lesson_public_id=lesson_public_id,
        ),
    )


def student_material_target(
    group_public_id, unit_public_id, lesson_public_id, material_public_id
):
    """The authorized Student page for one Material.

    A Material has no standalone Student page -- rich text and external
    links render inline on the Lesson page and a `file` Material is
    reached from there -- so this is the Lesson page anchored at
    ``#material-<public_id>``, exactly the destination M13 search already
    uses for a Material result. Public ids only.
    """
    return _validated(
        UserRole.STUDENT.value,
        _build_path(
            "student.lesson_detail",
            group_public_id=group_public_id,
            unit_public_id=unit_public_id,
            lesson_public_id=lesson_public_id,
        )
        + f"#material-{material_public_id}",
    )


def student_announcement_target(announcement_public_id):
    """The authorized Student detail page for one published Announcement
    (Phase 4 / M09).

    Public id only, resolved through the URL map like every other builder
    here. Passing validation is **not** authorization: the detail route
    re-proves the Student's current visibility of that announcement from
    scratch and returns the ordinary non-disclosing 404 when the
    Enrollment, the assignment or the academic chain has since ended --
    so an old notification can never become proof of access to a notice
    the recipient no longer stands in front of.
    """
    return _validated(
        UserRole.STUDENT.value,
        _build_path(
            "student.announcement_detail",
            announcement_public_id=announcement_public_id,
        ),
    )


def teacher_announcement_target(announcement_public_id):
    """The authorized Teacher detail page for one published Announcement
    (Phase 4 / M09). Same contract, and the same re-authorization on
    open, as the Student form."""
    return _validated(
        UserRole.TEACHER.value,
        _build_path(
            "teacher.announcement_detail",
            announcement_public_id=announcement_public_id,
        ),
    )


def role_announcement_target(role, announcement_public_id):
    """The announcement detail target for `role`, or ``None`` for a role
    without an inbox.

    Used by the announcement producer, whose recipients are a mix of
    Students and Teachers -- each is sent into **their own** role
    namespace, and an Administrator (who has no inbox in this project and
    is never a recipient) gets ``None`` rather than somebody else's path.
    """
    if role == UserRole.STUDENT.value:
        return student_announcement_target(announcement_public_id)
    if role == UserRole.TEACHER.value:
        return teacher_announcement_target(announcement_public_id)
    return None
