"""add notifications table for stored in-app notifications

Revision ID: 023a5f5814a8
Revises: ed1e6c7c2548
Create Date: 2026-09-02 01:08:39.226571

Additive only (M14): creates ``notifications`` and nothing else. No
existing table, column, index, constraint, or row is touched, and there
is no data backfill -- notifications only ever describe events that
happen *after* this migration runs, so pre-existing Enrollments,
assignments, Schedules, Lessons, and Materials deliberately produce no
historical rows.

The table holds one already-delivered, personal notification per row:
a UUID ``public_id`` (the only identifier that ever appears in a URL or
in HTML), a ``recipient_id`` FK into the shared ``users`` table, a
``kind`` constrained by ``ck_notifications_kind_valid`` to exactly the
seven M14 events, short plain-text ``title`` / ``message``, a
server-generated role-namespaced ``target_path``, a UTC ``created_at``,
and a nullable UTC ``read_at``.

Two composite indexes are created, because the two inbox filters sort on
different key suffixes:

- ``ix_notifications_recipient_unread_created`` (``recipient_id``,
  ``read_at``, ``created_at``) -- covers the header unread ``COUNT`` and
  orders the newest-first **unread** filter;
- ``ix_notifications_recipient_created_id`` (``recipient_id``,
  ``created_at``, ``id``) -- orders the newest-first **all** filter,
  which the unread index cannot satisfy without ``Using filesort``
  because ``read_at`` sits between the equality column and the sort
  columns.

Their shared ``recipient_id`` leftmost prefix is also what the
``recipient_id`` foreign key uses, so no separate single-column index is
created for it.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023a5f5814a8'
down_revision = 'ed1e6c7c2548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('target_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('enrollment_activated', 'enrollment_withdrawn', 'teacher_assignment_activated', 'teacher_assignment_removed', 'schedule_changed', 'lesson_published', 'material_available')", name='ck_notifications_kind_valid'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_recipient_created_id', ['recipient_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_notifications_recipient_unread_created', ['recipient_id', 'read_at', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropped in the reverse of the creation order above.
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_recipient_unread_created')
        batch_op.drop_index('ix_notifications_recipient_created_id')

    op.drop_table('notifications')
    # ### end Alembic commands ###
