"""Add groups table (Group belongs to AcademicTerm and Course)

Revision ID: 05f4be28f0ef
Revises: 8b85d0f1db85
Create Date: 2026-08-08 22:59:09.075177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f4be28f0ef'
down_revision = '8b85d0f1db85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('academic_term_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('course_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_groups_positive_capacity'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_term_id', 'course_id', 'code', name='uq_groups_term_course_code'),
    sa.UniqueConstraint('academic_term_id', 'course_id', 'name', name='uq_groups_term_course_name'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_academic_term_id'), ['academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_status'))
        batch_op.drop_index(batch_op.f('ix_groups_course_id'))
        batch_op.drop_index(batch_op.f('ix_groups_academic_term_id'))

    op.drop_table('groups')
    # ### end Alembic commands ###
