"""add materials, uploaded_files, file_access_logs tables

Revision ID: 8319232a5609
Revises: cb9112548dd6
Create Date: 2026-09-01 17:39:52.218654

Additive only (M12): creates ``uploaded_files``, ``file_access_logs``,
and ``materials`` -- a Material belongs directly to one Lesson and
optionally references one UploadedFile; an UploadedFile is referenced by
zero or more FileAccessLog rows. No existing table is touched. The ORM
relationship ``Lesson.materials`` needs no schema change on ``lessons``.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8319232a5609'
down_revision = 'cb9112548dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=120), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('document', 'image', 'audio', 'video')", name='ck_uploaded_files_category_valid'),
    sa.CheckConstraint('byte_size > 0', name='ck_uploaded_files_positive_size'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    op.create_table('file_access_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('uploaded_file_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('upload', 'inline', 'download')", name='ck_file_access_logs_action_valid'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_access_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_file_access_logs_file_time', ['uploaded_file_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_access_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_access_logs_uploaded_file_id'), ['uploaded_file_id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('uploaded_file_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('creation_nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(kind = 'rich_text' AND content_html IS NOT NULL AND external_url IS NULL AND uploaded_file_id IS NULL) OR (kind = 'external_link' AND external_url IS NOT NULL AND content_html IS NULL AND uploaded_file_id IS NULL) OR (kind = 'file' AND uploaded_file_id IS NOT NULL AND content_html IS NULL AND external_url IS NULL)", name='ck_materials_payload_matches_kind'),
    sa.CheckConstraint("kind IN ('rich_text', 'external_link', 'file')", name='ck_materials_kind_valid'),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_materials_status_valid'),
    sa.CheckConstraint('display_order >= 1', name='ck_materials_display_order_positive'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creation_nonce'),
    sa.UniqueConstraint('lesson_id', 'title', name='uq_materials_lesson_title'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('uploaded_file_id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_status'))
        batch_op.drop_index(batch_op.f('ix_materials_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_materials_display_order'))

    op.drop_table('materials')
    with op.batch_alter_table('file_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_access_logs_uploaded_file_id'))
        batch_op.drop_index(batch_op.f('ix_file_access_logs_occurred_at'))
        batch_op.drop_index('ix_file_access_logs_file_time')
        batch_op.drop_index(batch_op.f('ix_file_access_logs_actor_id'))

    op.drop_table('file_access_logs')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_created_at'))

    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
