"""Add academic core: academic_terms, levels, courses

Revision ID: 8b85d0f1db85
Revises: 982f3059f8aa
Create Date: 2026-08-08 01:17:04.956092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b85d0f1db85'
down_revision = '982f3059f8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('start_date < end_date', name='ck_academic_terms_valid_date_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('academic_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_terms_status'), ['status'], unique=False)

    op.create_table('levels',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_levels_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_levels_status'), ['status'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('level_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'code', name='uq_courses_level_id_code'),
    sa.UniqueConstraint('level_id', 'title', name='uq_courses_level_id_title'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_level_id'), ['level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index(batch_op.f('ix_courses_level_id'))
        batch_op.drop_index(batch_op.f('ix_courses_display_order'))

    op.drop_table('courses')
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_levels_status'))
        batch_op.drop_index(batch_op.f('ix_levels_display_order'))

    op.drop_table('levels')
    with op.batch_alter_table('academic_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_terms_status'))

    op.drop_table('academic_terms')
    # ### end Alembic commands ###
