"""Add schedules table for recurring group schedules

Revision ID: adf4b5691a7a
Revises: c8e88a1ef64a
Create Date: 2026-09-01 00:27:41.103590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf4b5691a7a'
down_revision = 'c8e88a1ef64a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('effective_end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_schedules_day_of_week_range'),
    sa.CheckConstraint('effective_start_date <= effective_end_date', name='ck_schedules_effective_date_order'),
    sa.CheckConstraint('start_time < end_time', name='ck_schedules_time_order'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'day_of_week', 'start_time', 'end_time', 'effective_start_date', 'effective_end_date', name='uq_schedules_exact_slot'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_status'))
        batch_op.drop_index(batch_op.f('ix_schedules_group_id'))

    op.drop_table('schedules')
    # ### end Alembic commands ###
