"""Add units table for group-owned teaching units

Revision ID: c3e39736023a
Revises: adf4b5691a7a
Create Date: 2026-09-01 03:51:43.063307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e39736023a'
down_revision = 'adf4b5691a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_units_display_order_non_negative'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'title', name='uq_units_group_title'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_status'))
        batch_op.drop_index(batch_op.f('ix_units_group_id'))
        batch_op.drop_index(batch_op.f('ix_units_display_order'))

    op.drop_table('units')
    # ### end Alembic commands ###
