"""Add group_teacher_assignments table

Revision ID: c8e88a1ef64a
Revises: d6ae31e9754c
Create Date: 2026-08-23 03:41:59.893215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e88a1ef64a'
down_revision = 'd6ae31e9754c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_teacher_assignments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('teacher_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'teacher_id', name='uq_group_teacher_assignments_group_teacher'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('group_teacher_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_teacher_assignments_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_teacher_assignments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_teacher_assignments_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_teacher_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_teacher_assignments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_group_teacher_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_group_teacher_assignments_group_id'))

    op.drop_table('group_teacher_assignments')
    # ### end Alembic commands ###
