"""add lessons table for unit-owned lessons

Revision ID: cb9112548dd6
Revises: c3e39736023a
Create Date: 2026-09-01 05:16:32.145107

Additive only (M11): creates the ``lessons`` table -- a Lesson belongs
directly to one Unit -- and touches no existing table. The ORM
relationship ``Unit.lessons`` needs no schema change on ``units``.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9112548dd6'
down_revision = 'c3e39736023a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(status = 'draft' AND published_at IS NULL) OR (status = 'published' AND published_at IS NOT NULL)", name='ck_lessons_status_published_at_consistency'),
    sa.CheckConstraint("status IN ('draft', 'published')", name='ck_lessons_status_valid'),
    sa.CheckConstraint('display_order >= 0', name='ck_lessons_display_order_non_negative'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('unit_id', 'title', name='uq_lessons_unit_title')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_unit_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_status'))
        batch_op.drop_index(batch_op.f('ix_lessons_display_order'))

    op.drop_table('lessons')
    # ### end Alembic commands ###
